name       : python-rarfile
version    : '3.0'
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/r/rarfile/rarfile-3.0.tar.gz : e816409e3b36794507cbe0b678bed3e4703d7412c5f7f9201a510ed6fdc66c35
license    : ISC
component  : programming.python
summary    : This is Python module for RAR archive reading
description: |
    This is Python module for RAR archive reading.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
