name       : python-rarfile
version    : '3.1'
release    : 3
source     :
    - https://files.pythonhosted.org/packages/88/0b/107dde3f330d04668e126932a09002ac47348841453aa0391634381fa087/rarfile-3.1.tar.gz : dc1062176c529f417522af7da1291a35b85c8017464e665aabce048cfe2659b6
license    : ISC
component  : programming.python
summary    : This is Python module for RAR archive reading
description: |
    This is Python module for RAR archive reading.
rundeps    :
    - python3-pycryptodome
build      : |
    %python3_setup
install    : |
    %python3_install
