name       : python-rarfile
version    : 2.8
release    : 1
source     :
    - https://pypi.python.org/packages/21/20/f07592dcf45f8f88a23c094019008ad220307401214a5c5a4e44d3e93acf/rarfile-2.8.tar.gz : 2a27e401daa6d8ff0df1112a274a3661ca3e4afaac626217506fb1391069ca61
license    : MIT
component  : programming.python
summary    : This is Python module for RAR archive reading.
description: |
    This is Python module for RAR archive reading.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
