name       : python-rarfile
version    : '4.0'
release    : 5
source     :
    - https://github.com/markokr/rarfile/releases/download/v4.0/rarfile-4.0.tar.gz : 67548769229c5bda0827c1663dce3f54644f9dbfba4ae86d4da2b2afd3e602a1
homepage   : https://github.com/markokr/rarfile
license    : ISC
component  : programming.python
summary    : This is Python module for RAR archive reading
description: |
    This is Python module for RAR archive reading. The interface follows the style of zipfile.
rundeps    :
    - python3-pycryptodome
build      : |
    %python3_setup
install    : |
    %python3_install
